### ISSUE TITLE
systems highlight crash when clearing ten trillion conveyors

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#1132]
```
2024-04-28 20:18:14.368 - Thread:   1 ->  Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at StarCore.SystemHighlight.SubsystemHighlight.ClearHighlight(List`1 blockList, IMyCubeGrid cubeGrid)
   at StarCore.SystemHighlight.SubsystemHighlight.HandleMessage(String message, Boolean& sendToOthers)
   at VRage.Game.ModAPI.MessageEnteredDel.Invoke(String messageText, Boolean& sendToOthers)
   at Sandbox.ModAPI.MyAPIUtilities.EnterMessage(UInt64 sender, String messageText, Boolean& sendToOthers)
   at Sandbox.Game.Gui.MyGuiScreenChat.OnInputFieldActivated(MyGuiControlTextbox textBox)
   at System.DelegateExtensions.InvokeIfNotNull[T1](Action`1 handler, T1 arg1)
   at Sandbox.Graphics.GUI.MyGuiControlTextbox.HandleInput()
   at Sandbox.Graphics.GUI.MyGuiScreenBase.HandleControlsInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyGuiScreenBase.HandleInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyScreenManager.HandleInput()
   at Sandbox.Graphics.GUI.MyDX9Gui.HandleInput()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   at avaness.SpaceEngineersLauncher.Program.StartSpaceEngineers(String[] args)
   at avaness.SpaceEngineersLauncher.Program.Main(String[] args)
   ```

**Comment by InvalidArgument3** [comment]
fixed in #1133
