### ISSUE TITLE
crash that points to seworldgen gpses after AI were fighting for ~9 minutes during a coordwriter recording

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#1153]
```
2024-05-09 01:42:13.887 - Thread:   1 ->  MEMORY VALUES,1,1,0,1,34,1141,44,127,273,385,3,7109,4488,0,0,106,4761,0,3749,31,0,50,15,3,33,7,0,476,758,0,0,30,0,0,0,0
2024-05-09 01:42:15.425 - Thread:   1 ->  DoDisconnects - 6052 0 6051
2024-05-09 01:42:15.447 - Thread:   1 ->  Info: Trash collector removed grid '119601316822719279:Large Grid 9279' with entity id '119601316822719279'
2024-05-09 01:42:15.447 - Thread:  13 ->  Entity Grid_D_Large_1 {1A8E8C393E31B2F} is closed.
2024-05-09 01:42:20.578 - Thread:   1 ->  DoDisconnects - 5985 0 5984
2024-05-09 01:42:22.106 - Thread:   1 ->  Info: Trash collector removed grid '141928493043346495:Large Grid 6495' with entity id '141928493043346495'
2024-05-09 01:42:22.198 - Thread:  38 ->  Exception occurred: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at System.Collections.Generic.Dictionary`2..ctor(IDictionary`2 dictionary, IEqualityComparer`1 comparer)
   at SEWorldGenPlugin.Generator.ProceduralGeneration.MyProceduralGeneratorComponent.UpdateGPS(Object stateInfo)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
```

**Comment by InvalidArgument3** [comment]
SEworldgen has been shadow realmed, it's not real anymore
