### ISSUE TITLE
world save and load edge case with sharetrack and npcs

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#1154]
```
2024-05-09 21:29:18.157 - Thread:   1 ->  Exception occurred: ParallelTasks.TaskException: An exception(s) was thrown while executing a task.
   at ParallelTasks.WorkItem.ThrowExceptionsInternal(Int32 runId)
   at ParallelTasks.Task.WaitOrExecute(Boolean blocking)
   at ParallelTasks.Parallel.For(Int32 startInclusive, Int32 endExclusive, Action`1 body, Int32 stride, WorkPriority priority, Nullable`1 options, Boolean blocking)
   at Sandbox.Game.Entities.MyEntities.Load_Patch2(List`1 objectBuilders, Nullable`1& errorMessage)
Task exception, inner exception 0:
System.InvalidOperationException: HudAPI: Failed to create backing object. Do not instantiate without checking if heartbeat is true.
   at Draygo.API.HudAPIv2.RegisterCheck()
   at Draygo.API.HudAPIv2.HUDMessage..ctor(StringBuilder Message, Vector2D origin, Nullable`1 offset, Int32 timeToLive, Double scale, Boolean hideHud, Boolean shadowing, Nullable`1 shadowColor, BlendTypeEnum blend, String font)
   at ShipPoints.ShipTracking.ShipTracker..ctor(IMyCubeGrid grid, Boolean showOnHud)
   at ShipPoints.ShipTracking.TrackingManager.TrackGrid(IMyCubeGrid grid, Boolean share)
   at ShipPoints.ShipTracking.TrackingManager.CheckAutotrack(IMySlimBlock block)
   at ShipPoints.ShipTracking.TrackingManager.<OnEntityAdd>b__8_0(IMySlimBlock block)
   at Sandbox.Game.Entities.MyCubeGrid.VRage.Game.ModAPI.IMyCubeGrid.GetBlocks(List`1 blocks, Func`2 collect)
   at ShipPoints.ShipTracking.TrackingManager.OnEntityAdd(IMyEntity entity)
   at System.Action`1.Invoke(T obj)
   at Sandbox.Game.Entities.MyEntities.RaiseEntityAdd(MyEntity entity)
   at Sandbox.Game.Entities.MyEntities.Add(MyEntity entity, Boolean insertIntoScene)
   at Sandbox.Game.Entities.MyEntities.InitEntityData.OnEntityInitialized()
   at Sandbox.Game.Entities.MyEntities.<>c__DisplayClass183_1.<Load>b__1(Int32 i)
   at ParallelTasks.ForLoopWork.DoWork(WorkData workData)
   at ParallelTasks.WorkItem.DoWork(Int32 expectedID)
   ```

**Comment by Jnick-24** [comment]
Resolved with #1212
