### ISSUE TITLE
PickMe System.InvalidCastException for adding point values

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#1165]
```
2024-05-14 01:56:19.317 - Thread:   1 ->  Exception occurred: System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.String,System.Int32]' to type 'System.Byte[]'.
   at PickMe.Session.AddPointValues(Object obj)
   at Sandbox.ModAPI.MyAPIUtilities.SendModMessage(Int64 id, Object payload)
   at ShipPoints.PointAdditions.Init(MyObjectBuilder_SessionComponent sessionComponent)
   at Sandbox.Game.World.MySession.InitDataComponents()
   at Sandbox.Game.World.MySession.LoadObjectBuildersComponents(List`1 objectBuilderData)
   at Sandbox.Game.World.MySession.PrepareBaseSession(MyObjectBuilder_Checkpoint checkpoint, MyObjectBuilder_Sector sector)
   at Sandbox.Game.World.MySession.LoadMultiplayer(MyObjectBuilder_World world, MyMultiplayerBase multiplayerSession)
   at System.DelegateExtensions.InvokeIfNotNull(Action handler)
   at Sandbox.Game.Gui.MyGuiScreenLoading.RunLoad()
```

**Comment by Jnick-24** [comment]
This is likely due to mod cache issues, could not replicate.

**Comment by InvalidArgument3** [comment]
it's back, i have snipped the brain stem of pickme in #1206 but steam is having a moment and the fix is not being pushed

**Comment by InvalidArgument3** [comment]
banishing pickme to the shadow realm for now
