### ISSUE TITLE
SystemsHighlight DS unload exception

### ISSUE THREAD

**Issue by Jnick-24** [StarCoreSE/SCModRepository#1200]
An exception is thrown when unloading a local Dedicated Server in the MTWorld.

```
024-05-31 19:03:19.708 - Thread:   1 ->  [ExceptionHandler] Mod unloaded.
--
2 | 2024-05-31 19:03:19.716 - Thread:   1 ->  [NetworkTimeSync] De-registered network message handler.
3 | 2024-05-31 19:03:19.717 - Thread:   1 ->  [MatchTimer] De-registered network message handler.
4 | 2024-05-31 19:03:19.734 - Thread:   1 ->  Exception occurred: VRage.Game.ModAPI.ModCrashedException: Mod crashed! ---> System.NullReferenceException: Object reference not set to an instance of an object.
5 | at StarCore.SystemHighlight.SubsystemHighlight.UnloadData()
6 | at Sandbox.Game.World.MySession.UnloadDataComponents(Boolean beforeLoadWorld)
7 | --- End of inner exception stack trace ---
8 | at Sandbox.Game.World.MySession.UnloadDataComponents(Boolean beforeLoadWorld)
9 | at Sandbox.Game.World.MySession.Unload()
10 | at Sandbox.MySandboxGame.UnloadData_UpdateThread()
11 | at Sandbox.MySandboxGame.EndLoop()
12 | at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
13 | at VRage.Dedicated.DedicatedServer.RunInternal(String instanceName)
14 | at VRage.Dedicated.DedicatedServer.RunMain(String instanceName, String customPath, Boolean isService, Boolean showConsole, Boolean checkAlive)
15 | at VRage.Dedicated.DedicatedServer.ProcessArgs(String[] args)
16 | at VRage.Dedicated.DedicatedServer.Run(String[] args, Action`1 initializeServices)
17 | at SpaceEngineersDedicated.MyProgram.Main(String[] args)
18 | 2024-05-31 19:03:19.735 - Thread:   1 ->  InnerException:
19 | 2024-05-31 19:03:19.735 - Thread:   1 ->  Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
20 | at StarCore.SystemHighlight.SubsystemHighlight.UnloadData()
21 | at Sandbox.Game.World.MySession.UnloadDataComponents(Boolean beforeLoadWorld)
22 | 2024-05-31 19:03:19.735 - Thread:   1 ->  Showing message
23 | 2024-05-31 19:03:19.737 - Thread:   1 ->  MyInitializer.OnCrash
24 | 2024-05-31 19:03:19.737 - Thread:   1 ->  var exception = VRage.Game.ModAPI.ModCrashedException: Mod crashed! ---> System.NullReferenceException: Object reference not set to an instance of an object.
25 | at StarCore.SystemHighlight.SubsystemHighlight.UnloadData()
26 | at Sandbox.Game.World.MySession.UnloadDataComponents(Boolean beforeLoadWorld)
27 | --- End of inner exception stack trace ---
28 | at Sandbox.Game.World.MySession.UnloadDataComponents(Boolean beforeLoadWorld)
29 | at Sandbox.Game.World.MySession.Unload()
30 | at Sandbox.MySandboxGame.UnloadData_UpdateThread()
31 | at Sandbox.MySandboxGame.EndLoop()
32 | at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
33 | at VRage.Dedicated.DedicatedServer.RunInternal(String instanceName)
34 | at VRage.Dedicated.DedicatedServer.RunMain(String instanceName, String customPath, Boolean isService, Boolean showConsole, Boolean checkAlive)
35 | at VRage.Dedicated.DedicatedServer.ProcessArgs(String[] args)
36 | at VRage.Dedicated.DedicatedServer.Run(String[] args, Action`1 initializeServices)
37 | at SpaceEngineersDedicated.MyProgram.Main(String[] args)
38 | 2024-05-31 19:03:36.946 - Thread:   1 ->  Log Closed
```

**Comment by CommodoreChet** [comment]
Closing until Replicated
