### ISSUE TITLE
[50$] the SharpDX sound crash

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#1278]
Need a way to reproduce this consistently.
Info:
- Occured after the Signal update when keen updated an audio subsystem
- happens in one of the following weapon packs: FAS, HAS, ONYX, SA
- likely crashes everyone in range when this "bad" sound plays
- narrowed down to something like a 0kb file in a weapon's audio.sbc is looped? but there are reports of a keen sound doing it too.

https://support.keenswh.com/spaceengineers/pc/topic/43473-sharpdx-sound-error-exceptions-from-vanilla-sounds

```
2024-07-21 01:36:11.415 - Thread:   1 ->  Exception occurred: SharpDX.SharpDXException: HRESULT: [0x88960001], Module: [SharpDX.XAudio2], ApiCode: [XAUDIO2_E_INVALID_CALL/InvalidCall], Message: Unknown
   at SharpDX.Result.CheckError()
   at SharpDX.XAudio2.SourceVoice.SubmitSourceBuffer(AudioBuffer bufferRef, Nullable`1 bufferWMARef)
   at SharpDX.XAudio2.SourceVoice.SubmitSourceBuffer(AudioBuffer bufferRef, UInt32[] decodedXMWAPacketInfo)
   at VRage.Audio.MySourceVoice.Start(Boolean skipIntro, Boolean skipToEnd)
   at VRage.Audio.MyXAudio2.PlaySound(MyCueId cueId, IMy3DSoundEmitter source, MySoundDimensions type, Boolean skipIntro, Boolean skipToEnd, Boolean isMusic)
   at VRage.Audio.MyXAudio2.VRage.Audio.IMyAudio.PlaySound(MyCueId cueId, IMy3DSoundEmitter source, MySoundDimensions type, Boolean skipIntro, Boolean skipToEnd)
   at Sandbox.Game.Entities.MyEntity3DSoundEmitter.PlaySoundInternal(Boolean skipIntro, Boolean skipToEnd, Boolean force2D, Boolean alwaysHearOnRealistic, Nullable`1 force3D)
2024-07-21 01:36:11.416 - Thread:   1 ->  Last null written by: Update3DCuesState
2024-07-21 01:36:11.428 - Thread:   1 ->  Exception: SharpDX.SharpDXException: HRESULT: [0x88960001], Module: [SharpDX.XAudio2], ApiCode: [XAUDIO2_E_INVALID_CALL/InvalidCall], Message: Unknown
   at SharpDX.Result.CheckError()
   at SharpDX.XAudio2.SourceVoice.SubmitSourceBuffer(AudioBuffer bufferRef, Nullable`1 bufferWMARef)
   at SharpDX.XAudio2.SourceVoice.SubmitSourceBuffer(AudioBuffer bufferRef, UInt32[] decodedXMWAPacketInfo)
   at VRage.Audio.MySourceVoice.Start(Boolean skipIntro, Boolean skipToEnd)
   at VRage.Audio.MyXAudio2.PlaySound(MyCueId cueId, IMy3DSoundEmitter source, MySoundDimensions type, Boolean skipIntro, Boolean skipToEnd, Boolean isMusic)
   at VRage.Audio.MyXAudio2.VRage.Audio.IMyAudio.PlaySound(MyCueId cueId, IMy3DSoundEmitter source, MySoundDimensions type, Boolean skipIntro, Boolean skipToEnd)
   at Sandbox.Game.Entities.MyEntity3DSoundEmitter.PlaySoundInternal(Boolean skipIntro, Boolean skipToEnd, Boolean force2D, Boolean alwaysHearOnRealistic, Nullable`1 force3D)
   at Sandbox.Game.Entities.MyEntity3DSoundEmitter.PlaySoundWithDistance(MyCueId soundId, Boolean stopPrevious, Boolean skipIntro, Boolean force2D, Boolean useDistanceCheck, Boolean alwaysHearOnRealistic, Boolean skipToEnd, Nullable`1 force3D)
   at Sandbox.Game.Entities.MyEntity3DSoundEmitter.PlaySound(MySoundPair soundId, Boolean stopPrevious, Boolean skipIntro, Boolean force2D, Boolean alwaysHearOnRealistic, Boolean skipToEnd, Nullable`1 force3D, Boolean forcePlaySound)
   at CoreSystems.Support.AvShot.HitEffects(Boolean force)
   at CoreSystems.Support.AvShot.DeferedAvStateUpdates()
   at CoreSystems.Projectiles.Projectiles.AvUpdate()
   at CoreSystems.Session.Simulate()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
2024-07-21 01:36:11.431 - Thread:   1 ->  Exception occurred: SharpDX.SharpDXException: HRESULT: [0x88960001], Module: [SharpDX.XAudio2], ApiCode: [XAUDIO2_E_INVALID_CALL/InvalidCall], Message: Unknown
   at SharpDX.Result.CheckError()
   at SharpDX.XAudio2.SourceVoice.SubmitSourceBuffer(AudioBuffer bufferRef, Nullable`1 bufferWMARef)
   at SharpDX.XAudio2.SourceVoice.SubmitSourceBuffer(AudioBuffer bufferRef, UInt32[] decodedXMWAPacketInfo)
   at VRage.Audio.MySourceVoice.Start(Boolean skipIntro, Boolean skipToEnd)
   at VRage.Audio.MyXAudio2.PlaySound(MyCueId cueId, IMy3DSoundEmitter source, MySoundDimensions type, Boolean skipIntro, Boolean skipToEnd, Boolean isMusic)
   at VRage.Audio.MyXAudio2.VRage.Audio.IMyAudio.PlaySound(MyCueId cueId, IMy3DSoundEmitter source, MySoundDimensions type, Boolean skipIntro, Boolean skipToEnd)
   at Sandbox.Game.Entities.MyEntity3DSoundEmitter.PlaySoundInternal(Boolean skipIntro, Boolean skipToEnd, Boolean force2D, Boolean alwaysHearOnRealistic, Nullable`1 force3D)
   at Sandbox.Game.Entities.MyEntity3DSoundEmitter.PlaySoundWithDistance(MyCueId soundId, Boolean stopPrevious, Boolean skipIntro, Boolean force2D, Boolean useDistanceCheck, Boolean alwaysHearOnRealistic, Boolean skipToEnd, Nullable`1 force3D)
   at Sandbox.Game.Entities.MyEntity3DSoundEmitter.PlaySound(MySoundPair soundId, Boolean stopPrevious, Boolean skipIntro, Boolean force2D, Boolean alwaysHearOnRealistic, Boolean skipToEnd, Nullable`1 force3D, Boolean forcePlaySound)
   at CoreSystems.Support.AvShot.HitEffects(Boolean force)
   at CoreSystems.Support.AvShot.DeferedAvStateUpdates()
   at CoreSystems.Projectiles.Projectiles.AvUpdate()
   at CoreSystems.Session.Simulate()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
2024-07-21 01:36:11.431 - Thread:   1 ->  Showing message
2024-07-21 01:36:11.431 - Thread:   1 ->  MyInitializer.OnCrash
2024-07-21 01:36:11.431 - Thread:   1 ->  var exception = SharpDX.SharpDXException: HRESULT: [0x88960001], Module: [SharpDX.XAudio2], ApiCode: [XAUDIO2_E_INVALID_CALL/InvalidCall], Message: Unknown
   at SharpDX.Result.CheckError()
   at SharpDX.XAudio2.SourceVoice.SubmitSourceBuffer(AudioBuffer bufferRef, Nullable`1 bufferWMARef)
   at SharpDX.XAudio2.SourceVoice.SubmitSourceBuffer(AudioBuffer bufferRef, UInt32[] decodedXMWAPacketInfo)
   at VRage.Audio.MySourceVoice.Start(Boolean skipIntro, Boolean skipToEnd)
   at VRage.Audio.MyXAudio2.PlaySound(MyCueId cueId, IMy3DSoundEmitter source, MySoundDimensions type, Boolean skipIntro, Boolean skipToEnd, Boolean isMusic)
   at VRage.Audio.MyXAudio2.VRage.Audio.IMyAudio.PlaySound(MyCueId cueId, IMy3DSoundEmitter source, MySoundDimensions type, Boolean skipIntro, Boolean skipToEnd)
   at Sandbox.Game.Entities.MyEntity3DSoundEmitter.PlaySoundInternal(Boolean skipIntro, Boolean skipToEnd, Boolean force2D, Boolean alwaysHearOnRealistic, Nullable`1 force3D)
   at Sandbox.Game.Entities.MyEntity3DSoundEmitter.PlaySoundWithDistance(MyCueId soundId, Boolean stopPrevious, Boolean skipIntro, Boolean force2D, Boolean useDistanceCheck, Boolean alwaysHearOnRealistic, Boolean skipToEnd, Nullable`1 force3D)
   at Sandbox.Game.Entities.MyEntity3DSoundEmitter.PlaySound(MySoundPair soundId, Boolean stopPrevious, Boolean skipIntro, Boolean force2D, Boolean alwaysHearOnRealistic, Boolean skipToEnd, Nullable`1 force3D, Boolean forcePlaySound)
   at CoreSystems.Support.AvShot.HitEffects(Boolean force)
   at CoreSystems.Support.AvShot.DeferedAvStateUpdates()
   at CoreSystems.Projectiles.Projectiles.AvUpdate()
   at CoreSystems.Session.Simulate()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   
   ```
   
   thanks keen
only way to fix this shit is scour every audio file for the one misconfigured .sbc or convert all weapon sounds to .xwm

**Comment by InvalidArgument3** [comment]
yeah we're going to just have to convert everything to .xwm

**Comment by InvalidArgument3** [comment]
got it a few times during 4.5 which contained the weapon packs of FAS, HAS, ONYX, SA. so it's one of those

**Comment by InvalidArgument3** [comment]
now a 50$ bounty on a setup that can reproduce this 100% of the time
https://support.keenswh.com/spaceengineers/pc/topic/43473-sharpdx-sound-error-exceptions-from-vanilla-sounds

**Comment by InvalidArgument3** [comment]
gottem

will need to go through with a script and change everything to 44100hz or wav

**Comment by InvalidArgument3** [comment]
"""fixed""" through the new ufucksounds.py script in the repo. keen has to do the rest
