### ISSUE TITLE
RTS index out of array

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#1281]
```
Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Collections.Generic.List`1.CopyTo(T[] array, Int32 arrayIndex)
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at RelativeTopSpeedGV.RelativeTopSpeed.<Simulate>b__26_1()
   at ParallelTasks.DelegateWork.DoWork(WorkData workData)
   at ParallelTasks.WorkItem.DoWork(Int32 expectedID)
2024-06-29 15:15:24.373 - Thread:   1 ->  Could not find any sound for 'RepairSound'
2024-06-29 15:15:26.076 - Thread:   1 ->  Could not find any sound for 'RepairSound'
2024-06-29 15:15:28.813 - Thread:  11 ->  Exception: System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Collections.Generic.List`1.CopyTo(T[] array, Int32 arrayIndex)
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at RelativeTopSpeedGV.RelativeTopSpeed.<Simulate>b__26_1()
   at ParallelTasks.DelegateWork.DoWork(WorkData workData)
   at ParallelTasks.WorkItem.DoWork(Int32 expectedID)
```

didnt crash the client but shows up in log

**Comment by InvalidArgument3** [comment]
y'know it's not hurting anybody so if it causes an actual crash that's when we can be worried

**Comment by BadM0dder** [comment]
Ask gauge to glance at it just in case?

**Comment by CommodoreChet** [comment]
The issue originates in a section not original to Gauges version
