### ISSUE TITLE
crash "something related to sharetrck and the AI blocks" when loading SP world under certain conditions

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#1293]
```
2024-07-01 00:56:34.129 - Thread:   1 ->  Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at ShipPoints.ShipTracking.ShipTracker.TransferToGrid(IMyCubeGrid newGrid)
   at ShipPoints.ShipTracking.ShipTracker..ctor(IMyCubeGrid grid, Boolean showOnHud)
   at ShipPoints.ShipTracking.TrackingManager.TrackGrid(IMyCubeGrid grid, Boolean share)
   at ShipPoints.ShipTracking.TrackingManager.CheckAutotrack(IMySlimBlock block)
   at ShipPoints.ShipTracking.TrackingManager.<OnEntityAdd>b__10_0(IMySlimBlock block)
   at Sandbox.Game.Entities.MyCubeGrid.VRage.Game.ModAPI.IMyCubeGrid.GetBlocks(List`1 blocks, Func`2 collect)
   at ShipPoints.ShipTracking.TrackingManager.OnEntityAdd(IMyEntity entity)
   at ShipPoints.ShipTracking.TrackingManager..ctor()
   at ShipPoints.ShipTracking.TrackingManager.Init()
   at ShipPoints.PointCheck.HudRegistered()
   at Draygo.API.HudAPIv2.RegisterComponents(Object obj)
   at Sandbox.ModAPI.MyAPIUtilities.SendModMessage(Int64 id, Object payload)
   at UIFun.FontTexture.Update()
   at UIFun.ModUI.Update()
   at UIFun.ModUI.Draw()
   at Sandbox.Game.World.MySession.DrawSync()
   at Sandbox.Game.Gui.MyGuiScreenGamePlay.Draw()
   at Sandbox.Graphics.GUI.MyScreenManager.DrawScreens(MyGuiScreenBase screenFade)
   at Sandbox.Graphics.GUI.MyScreenManager.Draw()
   at Sandbox.Graphics.GUI.MyDX9Gui.Draw()
   at Sandbox.Graphics.GUI.MyGuiSandbox.Draw()
   at Sandbox.MySandboxGame.PrepareForDraw()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
2024-07-01 00:56:34.131 - Thread:   1 ->  Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at ShipPoints.ShipTracking.ShipTracker.TransferToGrid(IMyCubeGrid newGrid)
   at ShipPoints.ShipTracking.ShipTracker..ctor(IMyCubeGrid grid, Boolean showOnHud)
   at ShipPoints.ShipTracking.TrackingManager.TrackGrid(IMyCubeGrid grid, Boolean share)
   at ShipPoints.ShipTracking.TrackingManager.CheckAutotrack(IMySlimBlock block)
   at ShipPoints.ShipTracking.TrackingManager.<OnEntityAdd>b__10_0(IMySlimBlock block)
   at Sandbox.Game.Entities.MyCubeGrid.VRage.Game.ModAPI.IMyCubeGrid.GetBlocks(List`1 blocks, Func`2 collect)
   at ShipPoints.ShipTracking.TrackingManager.OnEntityAdd(IMyEntity entity)
   at ShipPoints.ShipTracking.TrackingManager..ctor()
   at ShipPoints.ShipTracking.TrackingManager.Init()
   at ShipPoints.PointCheck.HudRegistered()
   at Draygo.API.HudAPIv2.RegisterComponents(Object obj)
   at Sandbox.ModAPI.MyAPIUtilities.SendModMessage(Int64 id, Object payload)
   at UIFun.FontTexture.Update()
   at UIFun.ModUI.Update()
   at UIFun.ModUI.Draw()
   at Sandbox.Game.World.MySession.DrawSync()
   at Sandbox.Game.Gui.MyGuiScreenGamePlay.Draw()
   at Sandbox.Graphics.GUI.MyScreenManager.DrawScreens(MyGuiScreenBase screenFade)
   at Sandbox.Graphics.GUI.MyScreenManager.Draw()
   at Sandbox.Graphics.GUI.MyDX9Gui.Draw()
   at Sandbox.Graphics.GUI.MyGuiSandbox.Draw()
   at Sandbox.MySandboxGame.PrepareForDraw()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
2024-07-01 00:56:34.131 - Thread:   1 ->  Showing message
2024-07-01 00:56:34.131 - Thread:   1 ->  MyInitializer.OnCrash
2024-07-01 00:56:34.131 - Thread:   1 ->  var exception = System.NullReferenceException: Object reference not set to an instance of an object.
   at ShipPoints.ShipTracking.ShipTracker.TransferToGrid(IMyCubeGrid newGrid)
   at ShipPoints.ShipTracking.ShipTracker..ctor(IMyCubeGrid grid, Boolean showOnHud)
   at ShipPoints.ShipTracking.TrackingManager.TrackGrid(IMyCubeGrid grid, Boolean share)
   at ShipPoints.ShipTracking.TrackingManager.CheckAutotrack(IMySlimBlock block)
   at ShipPoints.ShipTracking.TrackingManager.<OnEntityAdd>b__10_0(IMySlimBlock block)
   at Sandbox.Game.Entities.MyCubeGrid.VRage.Game.ModAPI.IMyCubeGrid.GetBlocks(List`1 blocks, Func`2 collect)
   at ShipPoints.ShipTracking.TrackingManager.OnEntityAdd(IMyEntity entity)
   at ShipPoints.ShipTracking.TrackingManager..ctor()
   at ShipPoints.ShipTracking.TrackingManager.Init()
   at ShipPoints.PointCheck.HudRegistered()
   at Draygo.API.HudAPIv2.RegisterComponents(Object obj)
   at Sandbox.ModAPI.MyAPIUtilities.SendModMessage(Int64 id, Object payload)
   at UIFun.FontTexture.Update()
   at UIFun.ModUI.Update()
   at UIFun.ModUI.Draw()
   at Sandbox.Game.World.MySession.DrawSync()
   at Sandbox.Game.Gui.MyGuiScreenGamePlay.Draw()
   at Sandbox.Graphics.GUI.MyScreenManager.DrawScreens(MyGuiScreenBase screenFade)
   at Sandbox.Graphics.GUI.MyScreenManager.Draw()
   at Sandbox.Graphics.GUI.MyDX9Gui.Draw()
   at Sandbox.Graphics.GUI.MyGuiSandbox.Draw()
   at Sandbox.MySandboxGame.PrepareForDraw()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
```

**Comment by InvalidArgument3** [comment]
crash in fresh starcore world with a spartan drone pasted down, saved and reloaded

```
2024-07-14 18:40:48.924 - Thread:   1 ->  Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at ShipPoints.ShipTracking.ShipTracker.TransferToGrid(IMyCubeGrid newGrid, Boolean showOnHud)
   at ShipPoints.ShipTracking.ShipTracker..ctor(IMyCubeGrid grid, Boolean showOnHud)
   at ShipPoints.ShipTracking.TrackingManager.TrackGrid(IMyCubeGrid grid, Boolean share)
   at ShipPoints.ShipTracking.TrackingManager.CheckAutotrack(IMySlimBlock block)
   at ShipPoints.ShipTracking.TrackingManager.<OnEntityAdd>b__10_0(IMySlimBlock block)
   at Sandbox.Game.Entities.MyCubeGrid.VRage.Game.ModAPI.IMyCubeGrid.GetBlocks(List`1 blocks, Func`2 collect)
   at ShipPoints.ShipTracking.TrackingManager.OnEntityAdd(IMyEntity entity)
   at ShipPoints.ShipTracking.TrackingManager..ctor()
   at ShipPoints.PointCheck.HudRegistered()
   at Draygo.API.HudAPIv2.RegisterComponents(Object obj)
   at Sandbox.ModAPI.MyAPIUtilities.SendModMessage(Int64 id, Object payload)
   at UIFun.FontTexture.Update()
   at UIFun.ModUI.Update()
   at Sandbox.Game.World.MySession.DrawSync()
   at Sandbox.Game.Gui.MyGuiScreenGamePlay.Draw()
   at Sandbox.Graphics.GUI.MyScreenManager.DrawScreens(MyGuiScreenBase screenFade)
   at Sandbox.Graphics.GUI.MyScreenManager.Draw()
   at Sandbox.Graphics.GUI.MyDX9Gui.Draw()
   at Sandbox.Graphics.GUI.MyGuiSandbox.Draw()
   at Sandbox.MySandboxGame.PrepareForDraw()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
2024-07-14 18:40:48.928 - Thread:   1 ->  Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at ShipPoints.ShipTracking.ShipTracker.TransferToGrid(IMyCubeGrid newGrid, Boolean showOnHud)
   at ShipPoints.ShipTracking.ShipTracker..ctor(IMyCubeGrid grid, Boolean showOnHud)
   at ShipPoints.ShipTracking.TrackingManager.TrackGrid(IMyCubeGrid grid, Boolean share)
   at ShipPoints.ShipTracking.TrackingManager.CheckAutotrack(IMySlimBlock block)
   at ShipPoints.ShipTracking.TrackingManager.<OnEntityAdd>b__10_0(IMySlimBlock block)
   at Sandbox.Game.Entities.MyCubeGrid.VRage.Game.ModAPI.IMyCubeGrid.GetBlocks(List`1 blocks, Func`2 collect)
   at ShipPoints.ShipTracking.TrackingManager.OnEntityAdd(IMyEntity entity)
   at ShipPoints.ShipTracking.TrackingManager..ctor()
   at ShipPoints.PointCheck.HudRegistered()
   at Draygo.API.HudAPIv2.RegisterComponents(Object obj)
   at Sandbox.ModAPI.MyAPIUtilities.SendModMessage(Int64 id, Object payload)
   at UIFun.FontTexture.Update()
   at UIFun.ModUI.Update()
   at Sandbox.Game.World.MySession.DrawSync()
   at Sandbox.Game.Gui.MyGuiScreenGamePlay.Draw()
   at Sandbox.Graphics.GUI.MyScreenManager.DrawScreens(MyGuiScreenBase screenFade)
   at Sandbox.Graphics.GUI.MyScreenManager.Draw()
   at Sandbox.Graphics.GUI.MyDX9Gui.Draw()
   at Sandbox.Graphics.GUI.MyGuiSandbox.Draw()
   at Sandbox.MySandboxGame.PrepareForDraw()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   at avaness.SpaceEngineersLauncher.Program.StartSpaceEngineers(String[] args)
   at avaness.SpaceEngineersLauncher.Program.Main(String[] args)
2024-07-14 18:40:48.928 - Thread:   1 ->  Showing message
2024-07-14 18:40:48.928 - Thread:   1 ->  MyInitializer.OnCrash
2024-07-14 18:40:48.928 - Thread:   1 ->  var exception = System.NullReferenceException: Object reference not set to an instance of an object.
   at ShipPoints.ShipTracking.ShipTracker.TransferToGrid(IMyCubeGrid newGrid, Boolean showOnHud)
   at ShipPoints.ShipTracking.ShipTracker..ctor(IMyCubeGrid grid, Boolean showOnHud)
   at ShipPoints.ShipTracking.TrackingManager.TrackGrid(IMyCubeGrid grid, Boolean share)
   at ShipPoints.ShipTracking.TrackingManager.CheckAutotrack(IMySlimBlock block)
   at ShipPoints.ShipTracking.TrackingManager.<OnEntityAdd>b__10_0(IMySlimBlock block)
   at Sandbox.Game.Entities.MyCubeGrid.VRage.Game.ModAPI.IMyCubeGrid.GetBlocks(List`1 blocks, Func`2 collect)
   at ShipPoints.ShipTracking.TrackingManager.OnEntityAdd(IMyEntity entity)
   at ShipPoints.ShipTracking.TrackingManager..ctor()
   at ShipPoints.PointCheck.HudRegistered()
   at Draygo.API.HudAPIv2.RegisterComponents(Object obj)
   at Sandbox.ModAPI.MyAPIUtilities.SendModMessage(Int64 id, Object payload)
   at UIFun.FontTexture.Update()
   at UIFun.ModUI.Update()
   at Sandbox.Game.World.MySession.DrawSync()
   at Sandbox.Game.Gui.MyGuiScreenGamePlay.Draw()
   at Sandbox.Graphics.GUI.MyScreenManager.DrawScreens(MyGuiScreenBase screenFade)
   at Sandbox.Graphics.GUI.MyScreenManager.Draw()
   at Sandbox.Graphics.GUI.MyDX9Gui.Draw()
   at Sandbox.Graphics.GUI.MyGuiSandbox.Draw()
   at Sandbox.MySandboxGame.PrepareForDraw()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   at avaness.SpaceEngineersLauncher.Program.StartSpaceEngineers(String[] args)
   at avaness.SpaceEngineersLauncher.Program.Main(String[] args)
```
