### ISSUE TITLE
WC crash potentially related to interception of projectiles

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#1341]
```
2024-07-08 23:43:36.556 - Thread:  14 ->  Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at CoreSystems.Support.Ai.FakeTarget.GetFakeTargetInfo(Ai ai)
   at CoreSystems.Platform.Weapon.ValidFakeTargetInfo(Int64 playerId, FakeWorldTargetInfo& fakeTargetInfo, Boolean preferPainted)
   at CoreSystems.Platform.Weapon.TrackingTarget(Weapon w, Target target, Boolean& targetLock)
   at CoreSystems.Session.<AimAi>b__859_0(Int32 i)
   at ParallelTasks.ForLoopWork.DoWork(WorkData workData)
   at ParallelTasks.WorkItem.DoWork(Int32 expectedID)
2024-07-08 23:43:36.563 - Thread:   1 ->  Exception: ParallelTasks.TaskException: An exception(s) was thrown while executing a task.
   at ParallelTasks.WorkItem.ThrowExceptionsInternal(Int32 runId)
   at ParallelTasks.Task.WaitOrExecute(Boolean blocking)
   at ParallelTasks.Parallel.For(Int32 startInclusive, Int32 endExclusive, Action`1 body, Int32 stride, WorkPriority priority, Nullable`1 options, Boolean blocking)
   at Sandbox.ModAPI.MyParallelTask.VRage.Game.ModAPI.IMyParallelTask.For(Int32 startInclusive, Int32 endExclusive, Action`1 body, Int32 stride)
   at CoreSystems.Session.AimAi()
   at CoreSystems.Session.Simulate()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
Task exception, inner exception 0:
System.NullReferenceException: Object reference not set to an instance of an object.
   at CoreSystems.Support.Ai.FakeTarget.GetFakeTargetInfo(Ai ai)
   at CoreSystems.Platform.Weapon.ValidFakeTargetInfo(Int64 playerId, FakeWorldTargetInfo& fakeTargetInfo, Boolean preferPainted)
   at CoreSystems.Platform.Weapon.TrackingTarget(Weapon w, Target target, Boolean& targetLock)
   at CoreSystems.Session.<AimAi>b__859_0(Int32 i)
   at ParallelTasks.ForLoopWork.DoWork(WorkData workData)
   at ParallelTasks.WorkItem.DoWork(Int32 expectedID)

2024-07-08 23:43:36.581 - Thread:   1 ->  Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at CoreSystems.Support.Ai.FakeTarget.GetFakeTargetInfo(Ai ai)
   at CoreSystems.Platform.Weapon.ValidFakeTargetInfo(Int64 playerId, FakeWorldTargetInfo& fakeTargetInfo, Boolean preferPainted)
   at CoreSystems.Platform.Weapon.TrackingTarget(Weapon w, Target target, Boolean& targetLock)
   at CoreSystems.Session.<AimAi>b__859_0(Int32 i)
   at ParallelTasks.ForLoopWork.DoWork(WorkData workData)
   at ParallelTasks.WorkItem.DoWork(Int32 expectedID)
2024-07-08 23:43:36.581 - Thread:   1 ->  Exception Data:
	Exception Info: Holder ID: 1486; m_runCount: 1486; m_executing: 1; MaximumThreads: 5
	Work Options: MaximumThreads: 5, QueueFIFO: False, DebugName: , TaskType: WorkItem
2024-07-08 23:43:36.581 - Thread:   1 ->  Task Exception Stack:
   at ParallelTasks.WorkItem.ThrowExceptionsInternal(Int32 runId)
   at ParallelTasks.Task.WaitOrExecute(Boolean blocking)
   at ParallelTasks.Parallel.For(Int32 startInclusive, Int32 endExclusive, Action`1 body, Int32 stride, WorkPriority priority, Nullable`1 options, Boolean blocking)
   at Sandbox.ModAPI.MyParallelTask.VRage.Game.ModAPI.IMyParallelTask.For(Int32 startInclusive, Int32 endExclusive, Action`1 body, Int32 stride)
   at CoreSystems.Session.AimAi()
   at CoreSystems.Session.Simulate()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   at avaness.SpaceEngineersLauncher.Program.StartSpaceEngineers(String[] args)
   at avaness.SpaceEngineersLauncher.Program.Main(String[] args)
2024-07-08 23:43:36.581 - Thread:   1 ->  Showing message
2024-07-08 23:43:36.581 - Thread:   1 ->  MyInitializer.OnCrash
2024-07-08 23:43:36.581 - Thread:   1 ->  var exception = ParallelTasks.TaskException: An exception(s) was thrown while executing a task.
   at ParallelTasks.WorkItem.ThrowExceptionsInternal(Int32 runId)
   at ParallelTasks.Task.WaitOrExecute(Boolean blocking)
   at ParallelTasks.Parallel.For(Int32 startInclusive, Int32 endExclusive, Action`1 body, Int32 stride, WorkPriority priority, Nullable`1 options, Boolean blocking)
   at Sandbox.ModAPI.MyParallelTask.VRage.Game.ModAPI.IMyParallelTask.For(Int32 startInclusive, Int32 endExclusive, Action`1 body, Int32 stride)
   at CoreSystems.Session.AimAi()
   at CoreSystems.Session.Simulate()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   at avaness.SpaceEngineersLauncher.Program.StartSpaceEngineers(String[] args)
   at avaness.SpaceEngineersLauncher.Program.Main(String[] args)
Task exception, inner exception 0:
System.NullReferenceException: Object reference not set to an instance of an object.
   at CoreSystems.Support.Ai.FakeTarget.GetFakeTargetInfo(Ai ai)
   at CoreSystems.Platform.Weapon.ValidFakeTargetInfo(Int64 playerId, FakeWorldTargetInfo& fakeTargetInfo, Boolean preferPainted)
   at CoreSystems.Platform.Weapon.TrackingTarget(Weapon w, Target target, Boolean& targetLock)
   at CoreSystems.Session.<AimAi>b__859_0(Int32 i)
   at ParallelTasks.ForLoopWork.DoWork(WorkData workData)
   at ParallelTasks.WorkItem.DoWork(Int32 expectedID)
```

**Comment by ari-steas** [comment]
haven't gotten in forever
