### ISSUE TITLE
WC crash when tait's stupid boat got rammed in half [still need to update our fork]

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#1431]
```
2024-07-26 03:20:17.522 - Thread:   1 ->  Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at WeaponCore.Data.Scripts.CoreSystems.Ui.Targeting.TargetUi.BuildMasterCollections(Ai ai)
   at WeaponCore.Data.Scripts.CoreSystems.Ui.Targeting.TargetUi.SelectTarget(Boolean manualSelect, Boolean firstStage, Boolean checkOnly)
   at WeaponCore.Data.Scripts.CoreSystems.Ui.Targeting.TargetUi.DrawSelector(Boolean enableActivator)
   at WeaponCore.Data.Scripts.CoreSystems.Ui.Targeting.TargetUi.ActivateSelector()
   at WeaponCore.Data.Scripts.CoreSystems.Ui.Targeting.TargetUi.DrawTargetUi()
   at CoreSystems.Session.Draw()
   at Sandbox.Game.World.MySession.DrawSync()
   at Sandbox.Game.Gui.MyGuiScreenGamePlay.Draw()
   at Sandbox.Graphics.GUI.MyScreenManager.DrawScreens(MyGuiScreenBase screenFade)
   at Sandbox.Graphics.GUI.MyScreenManager.Draw()
   at Sandbox.Graphics.GUI.MyDX9Gui.Draw()
   at Sandbox.Graphics.GUI.MyGuiSandbox.Draw()
   at Sandbox.MySandboxGame.PrepareForDraw()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
2024-07-26 03:20:17.591 - Thread:   1 ->  Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at WeaponCore.Data.Scripts.CoreSystems.Ui.Targeting.TargetUi.BuildMasterCollections(Ai ai)
   at WeaponCore.Data.Scripts.CoreSystems.Ui.Targeting.TargetUi.SelectTarget(Boolean manualSelect, Boolean firstStage, Boolean checkOnly)
   at WeaponCore.Data.Scripts.CoreSystems.Ui.Targeting.TargetUi.DrawSelector(Boolean enableActivator)
   at WeaponCore.Data.Scripts.CoreSystems.Ui.Targeting.TargetUi.ActivateSelector()
   at WeaponCore.Data.Scripts.CoreSystems.Ui.Targeting.TargetUi.DrawTargetUi()
   at CoreSystems.Session.Draw()
   at Sandbox.Game.World.MySession.DrawSync()
   at Sandbox.Game.Gui.MyGuiScreenGamePlay.Draw()
   at Sandbox.Graphics.GUI.MyScreenManager.DrawScreens(MyGuiScreenBase screenFade)
   at Sandbox.Graphics.GUI.MyScreenManager.Draw()
   at Sandbox.Graphics.GUI.MyDX9Gui.Draw()
   at Sandbox.Graphics.GUI.MyGuiSandbox.Draw()
   at Sandbox.MySandboxGame.PrepareForDraw()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   at avaness.SpaceEngineersLauncher.Program.StartSpaceEngineers(String[] args)
   at avaness.SpaceEngineersLauncher.Program.Main(String[] args)
2024-07-26 03:20:17.591 - Thread:   1 ->  Showing message
2024-07-26 03:20:17.591 - Thread:   1 ->  MyInitializer.OnCrash
2024-07-26 03:20:17.591 - Thread:   1 ->  var exception = System.NullReferenceException: Object reference not set to an instance of an object.
   at WeaponCore.Data.Scripts.CoreSystems.Ui.Targeting.TargetUi.BuildMasterCollections(Ai ai)
   at WeaponCore.Data.Scripts.CoreSystems.Ui.Targeting.TargetUi.SelectTarget(Boolean manualSelect, Boolean firstStage, Boolean checkOnly)
   at WeaponCore.Data.Scripts.CoreSystems.Ui.Targeting.TargetUi.DrawSelector(Boolean enableActivator)
   at WeaponCore.Data.Scripts.CoreSystems.Ui.Targeting.TargetUi.ActivateSelector()
   at WeaponCore.Data.Scripts.CoreSystems.Ui.Targeting.TargetUi.DrawTargetUi()
   at CoreSystems.Session.Draw()
   at Sandbox.Game.World.MySession.DrawSync()
   at Sandbox.Game.Gui.MyGuiScreenGamePlay.Draw()
   at Sandbox.Graphics.GUI.MyScreenManager.DrawScreens(MyGuiScreenBase screenFade)
   at Sandbox.Graphics.GUI.MyScreenManager.Draw()
   at Sandbox.Graphics.GUI.MyDX9Gui.Draw()
   at Sandbox.Graphics.GUI.MyGuiSandbox.Draw()
   at Sandbox.MySandboxGame.PrepareForDraw()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   at avaness.SpaceEngineersLauncher.Program.StartSpaceEngineers(String[] args)
   at avaness.SpaceEngineersLauncher.Program.Main(String[] args)
```

**Comment by InvalidArgument3** [comment]
fork updated
