### ISSUE TITLE
crash when a big ship got rammed in half

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#1482]
something related to updating energy;buildinfo;hud stats,keen?

```
2024-08-06 09:14:34.200 - Thread:   1 ->  Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Game.GUI.MyStatControlledEntityEnergyEstimatedTimeRemaining.Update()
   at Sandbox.Game.GUI.MyHudStatManager.Update()
   at Sandbox.Game.Gui.MyHud.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
2024-08-06 09:14:34.204 - Thread:   1 ->  Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Game.GUI.MyStatControlledEntityEnergyEstimatedTimeRemaining.Update()
   at Sandbox.Game.GUI.MyHudStatManager.Update()
   at Sandbox.Game.Gui.MyHud.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
2024-08-06 09:14:34.204 - Thread:   1 ->  Showing message
2024-08-06 09:14:34.204 - Thread:   1 ->  MyInitializer.OnCrash
2024-08-06 09:14:34.204 - Thread:   1 ->  var exception = System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Game.GUI.MyStatControlledEntityEnergyEstimatedTimeRemaining.Update()
   at Sandbox.Game.GUI.MyHudStatManager.Update()
   at Sandbox.Game.Gui.MyHud.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
```

**Comment by ari-steas** [comment]
hasn't cropped up since so closing for now
