### ISSUE TITLE
NRE from thruster fx mod

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#1496]
```
2024-08-05 13:44:24.155 - Thread:   1 ->  Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Blues_Thruster_Particles.CustomControls.GetThrusterColor(IMyTerminalBlock block)
   at Sandbox.Game.Gui.MyTerminalControlColor`1.OnUpdateVisual()
   at Sandbox.Game.Gui.MyTerminalControl`1.UpdateVisual()
   at Sandbox.Graphics.GUI.MyGuiControlGenericFunctionalBlock.RecreateBlockControls()
   at Sandbox.Graphics.GUI.MyGuiControlGenericFunctionalBlock..ctor(MyTerminalBlock[] blocks)
   at Sandbox.Game.Gui.MyTerminalControlPanel.SelectBlocks()
   at Sandbox.Game.Gui.MyTerminalControlPanel.blockListbox_ItemSelected(MyGuiControlListbox sender)
   at Sandbox.Graphics.GUI.MyGuiControlListbox.HandleNewMousePress(MyGuiControlBase& captureInput)
   at Sandbox.Graphics.GUI.MyGuiControlListbox.HandleInput()
   at Sandbox.Graphics.GUI.MyGuiControlParent.HandleInput()
   at Sandbox.Graphics.GUI.MyGuiControlParent.HandleInput()
   at Sandbox.Graphics.GUI.MyGuiScreenBase.HandleControlsInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyGuiScreenBase.HandleInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Game.Gui.MyGuiScreenTerminal.HandleInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyScreenManager.HandleInput()
   at Sandbox.Graphics.GUI.MyDX9Gui.HandleInput()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
```

**Comment by InvalidArgument3** [comment]
sprayfoamed in #1498
