### ISSUE TITLE
crash when adjusting a standalone fusion thruster power usage after reloading an sp world

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#1575]
```
2024-08-24 12:42:16.080 - Thread:   1 ->  Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at StarCore.FusionSystems.FusionParts.FusionPart`1.<>c.<CreateControls>b__20_5(IMyTerminalBlock block, Single value) in C:\Users\User\AppData\Roaming\SpaceEngineers\Mods\MoA Fusion Systems\Data\Scripts\ModularAssemblies\FusionParts\FusionPart.cs:line 101
   at Sandbox.Game.Screens.Terminal.Controls.MyTerminalValueControl`2.SetValue(TBlock block, TValue value)
   at Sandbox.Game.Gui.MyTerminalControlSlider`1.SetValue(Single value)
   at Sandbox.Game.Gui.MyTerminalControlSlider`1.OnValueChange(MyGuiControlSlider slider)
   at System.DelegateExtensions.InvokeIfNotNull[T1](Action`1 handler, T1 arg1)
   at Sandbox.Graphics.GUI.MyGuiControlSliderBase.set_Ratio(Single value)
   at Sandbox.Graphics.GUI.MyGuiControlSliderBase.HandleInput()
   at Sandbox.Graphics.GUI.MyGuiScreenBase.HandleControlsInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyGuiScreenBase.HandleInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Game.Gui.MyGuiScreenTerminal.HandleInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyScreenManager.HandleInput()
   at Sandbox.Graphics.GUI.MyDX9Gui.HandleInput()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
2024-08-24 12:42:16.085 - Thread:   1 ->  Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at StarCore.FusionSystems.FusionParts.FusionPart`1.<>c.<CreateControls>b__20_5(IMyTerminalBlock block, Single value) in C:\Users\User\AppData\Roaming\SpaceEngineers\Mods\MoA Fusion Systems\Data\Scripts\ModularAssemblies\FusionParts\FusionPart.cs:line 101
   at Sandbox.Game.Screens.Terminal.Controls.MyTerminalValueControl`2.SetValue(TBlock block, TValue value)
   at Sandbox.Game.Gui.MyTerminalControlSlider`1.SetValue(Single value)
   at Sandbox.Game.Gui.MyTerminalControlSlider`1.OnValueChange(MyGuiControlSlider slider)
   at System.DelegateExtensions.InvokeIfNotNull[T1](Action`1 handler, T1 arg1)
   at Sandbox.Graphics.GUI.MyGuiControlSliderBase.set_Ratio(Single value)
   at Sandbox.Graphics.GUI.MyGuiControlSliderBase.HandleInput()
   at Sandbox.Graphics.GUI.MyGuiScreenBase.HandleControlsInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyGuiScreenBase.HandleInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Game.Gui.MyGuiScreenTerminal.HandleInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyScreenManager.HandleInput()
   at Sandbox.Graphics.GUI.MyDX9Gui.HandleInput()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   at avaness.SpaceEngineersLauncher.Program.StartSpaceEngineers(String[] args)
   at avaness.SpaceEngineersLauncher.Program.Main(String[] args)
2024-08-24 12:42:16.085 - Thread:   1 ->  Showing message
2024-08-24 12:42:16.085 - Thread:   1 ->  MyInitializer.OnCrash
2024-08-24 12:42:16.085 - Thread:   1 ->  var exception = System.NullReferenceException: Object reference not set to an instance of an object.
   at StarCore.FusionSystems.FusionParts.FusionPart`1.<>c.<CreateControls>b__20_5(IMyTerminalBlock block, Single value) in C:\Users\User\AppData\Roaming\SpaceEngineers\Mods\MoA Fusion Systems\Data\Scripts\ModularAssemblies\FusionParts\FusionPart.cs:line 101
   at Sandbox.Game.Screens.Terminal.Controls.MyTerminalValueControl`2.SetValue(TBlock block, TValue value)
   at Sandbox.Game.Gui.MyTerminalControlSlider`1.SetValue(Single value)
   at Sandbox.Game.Gui.MyTerminalControlSlider`1.OnValueChange(MyGuiControlSlider slider)
   at System.DelegateExtensions.InvokeIfNotNull[T1](Action`1 handler, T1 arg1)
   at Sandbox.Graphics.GUI.MyGuiControlSliderBase.set_Ratio(Single value)
   at Sandbox.Graphics.GUI.MyGuiControlSliderBase.HandleInput()
   at Sandbox.Graphics.GUI.MyGuiScreenBase.HandleControlsInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyGuiScreenBase.HandleInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Game.Gui.MyGuiScreenTerminal.HandleInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyScreenManager.HandleInput()
   at Sandbox.Graphics.GUI.MyDX9Gui.HandleInput()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   at avaness.SpaceEngineersLauncher.Program.StartSpaceEngineers(String[] args)
   at avaness.SpaceEngineersLauncher.Program.Main(String[] args)
```

**Comment by InvalidArgument3** [comment]
this is apparently due to the mexpex thruster framework doing something to thrusters, was trying to make a better effect
will explore later
