### ISSUE TITLE
Exhaust Block Crash

### ISSUE THREAD

**Issue by CommodoreChet** [StarCoreSE/SCModRepository#1853]
2024-12-14 17:22:58.003 - Thread:   1 ->  Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Game.Entities.Blocks.MyExhaustBlock.UpdateAfterSimulation()
   at Sandbox.Game.Entities.MyParallelEntityUpdateOrchestrator.UpdateAfterSimulation()
   at Sandbox.Game.Entities.MyParallelEntityUpdateOrchestrator.DispatchAfterSimulation()
   at Sandbox.Game.Entities.MyEntities.UpdateAfterSimulation()
   at Sandbox.Game.World.MySector.UpdateAfterSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   
   Crash when Exhaust Block was Destroyed
   Rejoining Server results in a Hard Crash on first try, second try works.

**Comment by ari-steas** [comment]
Proposed solution is to blockrestrict them in the new S5 world.
