### ISSUE TITLE
paperdoll crash when rendering vessels with active automaton AI blocks

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#231]
2023-10-15 15:13:47.826 - Thread:   1 ->  Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Game.AI.CollisionAvoidance.MyAutopilotCollisionAvoidance.AvoidCollisions(MyTerminalBlock blockForPositionReference, Single thrusterForce, Vector3D delta, Single& autopilotSpeedLimit, Vector3D targetPosition, Boolean waitForFreeWay)
   at Sandbox.Game.EntityComponents.MyAutopilotComponent.CalculateDeltaPos(MyEntityThrustComponent thrust, Vector3D targetPos, Vector3D& deltaPos, Vector3D& perpDeltaPos, Vector3D& targetDelta, Single& autopilotSpeedLimit, Boolean& isCollisionAvoidance)
   at Sandbox.Game.EntityComponents.MyAutopilotComponent.UpdateAutopilot()
   at Sandbox.Game.Entities.MyParallelEntityUpdateOrchestrator.ParallelUpdateHandlerBeforeSimulation(IMyParallelUpdateable entity)
   at ParallelTasks.ForEachLoopWork`1.DoWork(WorkData workData)
   at ParallelTasks.WorkItem.DoWork(Int32 expectedID)
2023-10-15 15:13:47.826 - Thread:   1 ->  Exception Data:
	Exception Info: Holder ID: 1682; m_runCount: 1682; m_executing: 4; MaximumThreads: 2147483647
	Work Options: MaximumThreads: 2147483647, QueueFIFO: False, DebugName: , TaskType: WorkItem
2023-10-15 15:13:47.827 - Thread:   1 ->  Task Exception Stack:
   at ParallelTasks.WorkItem.ThrowExceptionsInternal(Int32 runId)
   at ParallelTasks.Task.WaitOrExecute(Boolean blocking)
   at ParallelTasks.Parallel.ForEach[T](IEnumerable`1 collection, Action`1 action, WorkPriority priority, Nullable`1 options, Boolean blocking)
   at Sandbox.Game.Entities.MyParallelEntityUpdateOrchestrator.PerformParallelUpdate(Action`1 updateFunction)
   at Sandbox.Game.Entities.MyParallelEntityUpdateOrchestrator.DispatchBeforeSimulation()
   at Sandbox.Game.Entities.MyEntities.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySector.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   at avaness.SpaceEngineersLauncher.Program.StartSpaceEngineers(String[] args)
   at avaness.SpaceEngineersLauncher.Program.Main(String[] args)
2023-10-15 15:13:47.827 - Thread:   1 ->  Showing message

**Comment by InvalidArgument3** [comment]
its specifically the pathfinding on remote controls and the AI flight movement block, collision avoidance. turn them off in the object builder. turn them off in the objectbuilder before spawning as entity.
