### ISSUE TITLE
blink drive final solution

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#255]
- need to avoid clipping into entities
- base mod's "avoid entities" .cfg option does not update on clients (it works, stops you from tp'ing into blocks, but doesnt force it on clientside

options:
- fork and fix it
- add a failsafe inside the blockers to just push you out

**Comment by InvalidArgument3** [comment]
i cannot comprehend how to check a specific dimension without relying on phantom's intersection check

**Comment by InvalidArgument3** [comment]
reopening this, we need our own solution.

**Comment by InvalidArgument3** [comment]
about to fix this, error log for future reference

```
2024-02-04 19:36:55.647 - Thread:   1 ->  Exception occurred: SharpDX.SharpDXException: HRESULT: [0x88960001], Module: [SharpDX.XAudio2], ApiCode: [XAUDIO2_E_INVALID_CALL/InvalidCall], Message: Unknown
   at SharpDX.Result.CheckError()
   at SharpDX.XAudio2.SourceVoice.SubmitSourceBuffer(AudioBuffer bufferRef, Nullable`1 bufferWMARef)
   at SharpDX.XAudio2.SourceVoice.SubmitSourceBuffer(AudioBuffer bufferRef, UInt32[] decodedXMWAPacketInfo)
   at VRage.Audio.MySourceVoice.Start(Boolean skipIntro, Boolean skipToEnd)
   at VRage.Audio.MyXAudio2.PlaySound(MyCueId cueId, IMy3DSoundEmitter source, MySoundDimensions type, Boolean skipIntro, Boolean skipToEnd, Boolean isMusic)
   at VRage.Audio.MyXAudio2.VRage.Audio.IMyAudio.PlaySound(MyCueId cueId, IMy3DSoundEmitter source, MySoundDimensions type, Boolean skipIntro, Boolean skipToEnd)
   at Sandbox.Game.Entities.MyEntity3DSoundEmitter.PlaySoundInternal(Boolean skipIntro, Boolean skipToEnd, Boolean force2D, Boolean alwaysHearOnRealistic, Nullable`1 force3D)
2024-02-04 19:36:55.647 - Thread:   1 ->  Last null written by: 
2024-02-04 19:36:56.161 - Thread:   1 ->  Exception occurred: SharpDX.SharpDXException: HRESULT: [0x88960001], Module: [SharpDX.XAudio2], ApiCode: [XAUDIO2_E_INVALID_CALL/InvalidCall], Message: Unknown
   at SharpDX.Result.CheckError()
   at SharpDX.XAudio2.SourceVoice.SubmitSourceBuffer(AudioBuffer bufferRef, Nullable`1 bufferWMARef)
   at SharpDX.XAudio2.SourceVoice.SubmitSourceBuffer(AudioBuffer bufferRef, UInt32[] decodedXMWAPacketInfo)
   at VRage.Audio.MySourceVoice.Start(Boolean skipIntro, Boolean skipToEnd)
   at VRage.Audio.MyXAudio2.PlaySound(MyCueId cueId, IMy3DSoundEmitter source, MySoundDimensions type, Boolean skipIntro, Boolean skipToEnd, Boolean isMusic)
   at VRage.Audio.MyXAudio2.VRage.Audio.IMyAudio.PlaySound(MyCueId cueId, IMy3DSoundEmitter source, MySoundDimensions type, Boolean skipIntro, Boolean skipToEnd)
   at Sandbox.Game.Entities.MyEntity3DSoundEmitter.PlaySoundInternal(Boolean skipIntro, Boolean skipToEnd, Boolean force2D, Boolean alwaysHearOnRealistic, Nullable`1 force3D)
   at Sandbox.Game.Entities.MyEntity3DSoundEmitter.PlaySoundWithDistance(MyCueId soundId, Boolean stopPrevious, Boolean skipIntro, Boolean force2D, Boolean useDistanceCheck, Boolean alwaysHearOnRealistic, Boolean skipToEnd, Nullable`1 force3D)
   at Sandbox.Game.Entities.MyEntity3DSoundEmitter.PlaySingleSound(MySoundPair soundId, Boolean stopPrevious, Boolean skipIntro, Boolean skipToEnd, Nullable`1 force3D)
   at BlinkDrive.BlinkDrive.DoJump()
   at BlinkDrive.BlinkDrive.UpdateBlinkSequence()
   at BlinkDrive.BlinkDrive.UpdateBeforeSimulation()
   at VRage.Game.Components.MyGameLogicComponent.VRage.Game.Entity.EntityComponents.Interfaces.IMyGameLogicComponent.UpdateBeforeSimulation(Boolean entityUpdate)
   at Sandbox.Game.Entities.MyCubeBlock.UpdateBeforeSimulation()
   at Sandbox.Game.Entities.MyParallelEntityUpdateOrchestrator.UpdateBeforeSimulation()
   at Sandbox.Game.Entities.MyParallelEntityUpdateOrchestrator.DispatchBeforeSimulation()
   at Sandbox.Game.Entities.MyEntities.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySector.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   at avaness.SpaceEngineersLauncher.Program.StartSpaceEngineers(String[] args)
   at avaness.SpaceEngineersLauncher.Program.Main(String[] args)
   ```

**Comment by InvalidArgument3** [comment]
it's over
