### ISSUE TITLE
NullReferenceException crash when right clicking a collector on a grid with the S.I field gen due to terminal actions

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#262]
**Steps to reproduce:**
1. place SI fieldgen on a g rid
2. place collector on grid
3. place cockpit on grid
4. get in cockpit and right-click the connector

**Log Files:**
```
2023-12-16 04:19:34.009 - Thread:   1 ->  Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at StarCore.StructuralIntegrity.SI_Core.Siege_Enabled_Enabler(IMyTerminalBlock block) in C:\Users\User\AppData\Roaming\SpaceEngineers\Mods\SCDefenseBlocks\Data\Scripts\StructuralIntegrity\SI_Core.cs:line 843
   at Sandbox.Game.Gui.MyTerminalAction`1.IsEnabled(MyTerminalBlock block)
   at Sandbox.Game.Screens.Helpers.MyToolbarItemTerminalBlock.GetActions(Nullable`1 type)
   at Sandbox.Game.Screens.Helpers.MyToolbarItemTerminalBlock.get_AllActions()
   at Sandbox.Game.Screens.Helpers.MyToolbarItemActions.SetAction(String action)
   at Sandbox.Game.Screens.Helpers.MyToolbarItemTerminalBlock.Init(MyObjectBuilder_ToolbarItem objectBuilder)
   at Sandbox.Game.Screens.Helpers.MyToolbarItemFactory.CreateToolbarItem(MyObjectBuilder_ToolbarItem data)
   at Sandbox.Game.Gui.MyGuiScreenToolbarConfigBase.grid_ItemClicked(MyGuiControlGrid sender, EventArgs eventArgs)
   at Sandbox.Graphics.GUI.MyGuiControlGrid.HandleNewMousePress(MyGuiControlBase& captureInput)
   at Sandbox.Graphics.GUI.MyGuiControlGrid.HandleInput()
   at Sandbox.Graphics.GUI.MyGuiControlBase.HandleInputElements()
   at Sandbox.Graphics.GUI.MyGuiControlScrollablePanel.HandleInput()
   at Sandbox.Graphics.GUI.MyGuiControlParent.HandleInput()
   at Sandbox.Graphics.GUI.MyGuiControlParent.HandleInput()
   at Sandbox.Graphics.GUI.MyGuiScreenBase.HandleControlsInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyGuiScreenBase.HandleInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Game.Gui.MyGuiScreenToolbarConfigBase.HandleInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyScreenManager.HandleInput()
   at Sandbox.Graphics.GUI.MyDX9Gui.HandleInput()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   at avaness.SpaceEngineersLauncher.Program.StartSpaceEngineers(String[] args)
   at avaness.SpaceEngineersLauncher.Program.Main(String[] args)

```

**Comment by InvalidArgument3** [comment]
fixed ;)
