### ISSUE TITLE
sifieldgen fails to init its ui then stops the world from saving while it exists

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#297]
what the fuck

on block placement:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at StarCore.StructuralIntegrity.SI_Core.SetupTerminalControls[T](Single minDivertedPower, Single maxDivertedPower) in C:\Users\User\AppData\Roaming\SpaceEngineers\Mods\SCDefenseBlocks\Data\Scripts\StructuralIntegrity\SI_Core.cs:line 682
   at StarCore.StructuralIntegrity.SI_Core.UpdateOnceBeforeFrame() in C:\Users\User\AppData\Roaming\SpaceEngineers\Mods\SCDefenseBlocks\Data\Scripts\StructuralIntegrity\SI_Core.cs:line 157
```
   
 on world attempted save:
 
 
```
   2024-01-03 06:09:21.810 - Thread:   1 ->     Exception occurred: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at VRage.Game.Components.MyComponentContainer.Serialize(Boolean copy)
   at Sandbox.Game.Entities.MyCubeBlock.GetObjectBuilderCubeBlock(Boolean copy)
   at Sandbox.Game.Entities.Cube.MyTerminalBlock.GetObjectBuilderCubeBlock(Boolean copy)
   at Sandbox.Game.Entities.Cube.MyFunctionalBlock.GetObjectBuilderCubeBlock(Boolean copy)
   at Sandbox.Game.Entities.Blocks.MyCollector.GetObjectBuilderCubeBlock(Boolean copy)
   at Sandbox.Game.Entities.Cube.MySlimBlock.GetObjectBuilderInternal(Boolean copy)
   at Sandbox.Game.Entities.MyCubeGrid.GetObjectBuilderInternal(MyObjectBuilder_CubeGrid ob, Boolean copy)
   at Sandbox.Game.Entities.MyCubeGrid.GetObjectBuilder(Boolean copy)
   at Sandbox.Game.Entities.MyEntities.Save()
   at Sandbox.Game.World.MySession.GetSector(Boolean includeEntities)
   at Sandbox.Game.World.MySession.Save(MySessionSnapshot& snapshot, String customSaveName, Action`1 progress)
2024-01-03 06:09:21.813 - Thread:   1 ->  OnSnapshotDone: failed to save the world    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at Sandbox.Game.Screens.Helpers.MyAsyncSaving.OnSnapshotDone(Boolean snapshotSuccess, MySessionSnapshot snapshot)
   at Sandbox.Game.Screens.Helpers.MyAsyncSaving.Start(Action callbackOnFinished, String customName)
   at Sandbox.Game.Gui.MyGuiScreenGamePlay.<>c.<HandleUnhandledInput>b__49_18(ResultEnum callbackReturn)
   at Sandbox.Graphics.GUI.MyGuiScreenMessageBox.CallResultCallback(ResultEnum val)
   at System.DelegateExtensions.InvokeIfNotNull[T1](Action`1 handler, T1 arg1)
   at Sandbox.Graphics.GUI.MyGuiControlButton.HandleInput()
   at Sandbox.Graphics.GUI.MyGuiScreenBase.HandleControlsInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyGuiScreenBase.HandleInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyGuiScreenMessageBox.HandleInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyScreenManager.HandleInput()
   at Sandbox.Graphics.GUI.MyDX9Gui.HandleInput()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   at avaness.SpaceEngineersLauncher.Program.StartSpaceEngineers(String[] args)
   at avaness.SpaceEngineersLauncher.Program.Main(String[] args)
```

**Comment by InvalidArgument3** [comment]
this worked like two days ago wtf right after #262
