### ISSUE TITLE
unknown rare serverside freeze during grid removal

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#491]
watch out for "global" modscripts that do something about grid removal
- mods that check damage events: DamageInfo (not this one), sharetrack, paperdoll, etc.

squid reports it died when he ctrl x'd a grid

**Comment by BDCarrillo** [comment]
DamageInfo does not hook any grid removal events.  Is there a log?

**Comment by InvalidArgument3** [comment]
> DamageInfo does not hook any grid removal events. Is there a log?

the server just suddenly freezes until the watchdog kills it, no logs are retrievable

**Comment by InvalidArgument3** [comment]
happened again during a match, log complains about the coordinate mod on a parallel thread, but it happened before then

```
16:14:17.4544 [INFO]   Torch.Commands.CommandManager: Server ran command '!restart cancel'
16:14:39.5549 [INFO]   Chat: [Global:0] Invalid: teams ready?
16:14:46.8387 [INFO]   Chat: [Global:0] natedawg: just put older ones in
16:14:57.6386 [INFO]   Chat: [Global:0] natedawg: yeah ready
16:15:10.3216 [INFO]   Chat: [Global:0] Invalid: 4
16:15:11.0547 [INFO]   Chat: [Global:0] Invalid: 3
16:15:11.8717 [INFO]   Chat: [Global:0] Invalid: 2
16:15:12.5880 [INFO]   Chat: [Global:0] Invalid: 1
16:15:14.4812 [INFO]   Chat: [Global:0] Invalid: /start
16:15:15.6721 [INFO]   Chat: [Global:0] Invalid: go
16:17:36.4644 [ERROR]  Keen: Mod SCCoordinateOutput is accessing physics from parallel threads. This is not safe and might cause the game to crash or behave unexpectedly.
16:19:18.2224 [INFO]   Torch.Commands.CommandManager: Server ran command '!restart cancel'
16:20:26.3539 [INFO]   Chat: [Global:0] Tiberias: Mr. Torgue demands more explosions
16:20:30.0202 [INFO]   Chat: [Global:0] Invalid: GRUDGE match not CRINGE match ok
16:20:45.1697 [INFO]   Chat: [Global:0] Tiberias: ^ what he said
16:20:48.0867 [INFO]   Chat: [Global:0] Dylan Dawn: game of chess \o/
16:23:44.6161 [ERROR]  Torch: Frozen thread dump Main thread
Common prefix:
   at Scripts.Session.ShouldProcessEntity(MyEntity ent)
   at Scripts.Session.<UpdateBeforeSimulation>b__13_0(Int32 i)
   at ParallelTasks.ForLoopWork.DoWork(WorkData workData)
   at ParallelTasks.WorkItem.DoWork(Int32 expectedID)
   at ParallelTasks.Task.WaitOrExecute(Boolean blocking)
   at ParallelTasks.Parallel.For(Int32 startInclusive, Int32 endExclusive, Action`1 body, Int32 stride, WorkPriority priority, Nullable`1 options, Boolean blocking)
   at Sandbox.ModAPI.MyParallelTask.VRage.Game.ModAPI.IMyParallelTask.For(Int32 startInclusive, Int32 endExclusive, Action`1 body)
   at Scripts.Session.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 326
   at Torch.VRageGame.Run() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 126
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Suffix 0
   at System.Collections.Generic.HashSet`1.Contains(T item)

Suffix 1
   at System.Collections.Generic.HashSet`1.Contains(T item)

Suffix 2
   at System.Collections.Generic.HashSet`1.Contains(T item)


16:23:44.6161 [FATAL]  Initializer: System.TimeoutException: Server watchdog detected that the server was frozen for at least 60 seconds.
   at Torch.Server.TorchServer.CheckServerResponding(Object state) in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch.Server\TorchServer.cs:line 301
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
System.TimeoutException: Server watchdog detected that the server was frozen for at least 60 seconds.
   at Torch.Server.TorchServer.CheckServerResponding(Object state) in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch.Server\TorchServer.cs:line 301
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   ```

**Comment by CommodoreChet** [comment]
Closing. Potentially Fixed with a rewrite of coordwriter that removed bad multithreading
