### ISSUE TITLE
WeaponCore-StarCore: NullReferenceException on drawing targeting UI

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#507]
happened "when tibs got hit so hard he split into 3 parts and all of his cockpits were destroyed"
```
2024-02-08 19:45:01.041 - Thread:   1 ->  Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at WeaponCore.Data.Scripts.CoreSystems.Ui.Targeting.TargetUi.SelectTarget(Boolean manualSelect, Boolean firstStage, Boolean checkOnly)
   at WeaponCore.Data.Scripts.CoreSystems.Ui.Targeting.TargetUi.DrawSelector(Boolean enableActivator)
   at WeaponCore.Data.Scripts.CoreSystems.Ui.Targeting.TargetUi.ActivateSelector()
   at WeaponCore.Data.Scripts.CoreSystems.Ui.Targeting.TargetUi.DrawTargetUi()
   at CoreSystems.Session.Draw()
   at Sandbox.Game.World.MySession.DrawSync()
   at Sandbox.Game.Gui.MyGuiScreenGamePlay.Draw()
   at Sandbox.Graphics.GUI.MyScreenManager.DrawScreens(MyGuiScreenBase screenFade)
   at Sandbox.Graphics.GUI.MyScreenManager.Draw()
   at Sandbox.Graphics.GUI.MyDX9Gui.Draw()
   at Sandbox.Graphics.GUI.MyGuiSandbox.Draw()
   at Sandbox.MySandboxGame.PrepareForDraw()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   at avaness.SpaceEngineersLauncher.Program.StartSpaceEngineers(String[] args)
   at avaness.SpaceEngineersLauncher.Program.Main(String[] args)
   ```

**Comment by Tiberias42** [comment]
Ill try to not do that anymore
