### ISSUE TITLE
null reference exception due to new recolorable thruster mod

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#609]
happened to loldude while just sitting in his grid while in a menu

```
2024-02-28 03:10:17.936 - Thread:   1 ->  Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at Blues_Thruster_Particles.CustomControls.GetThrusterColor(IMyTerminalBlock block)
   at Sandbox.Game.Gui.MyTerminalControlColor`1.OnUpdateVisual()
   at Sandbox.Game.Gui.MyTerminalControl`1.UpdateVisual()
   at Sandbox.Graphics.GUI.MyGuiControlGenericFunctionalBlock.RecreateBlockControls()
   at Sandbox.Graphics.GUI.MyGuiControlGenericFunctionalBlock..ctor(MyTerminalBlock[] blocks)
   at Sandbox.Game.Gui.MyTerminalControlPanel.SelectBlocks()
   at Sandbox.Game.Gui.MyTerminalControlPanel.blockListbox_ItemSelected(MyGuiControlListbox sender)
   at Sandbox.Graphics.GUI.MyGuiControlListbox.HandleNewMousePress(MyGuiControlBase& captureInput)
   at Sandbox.Graphics.GUI.MyGuiControlListbox.HandleInput()
   at Sandbox.Graphics.GUI.MyGuiControlParent.HandleInput()
   at Sandbox.Graphics.GUI.MyGuiControlParent.HandleInput()
   at Sandbox.Graphics.GUI.MyGuiScreenBase.HandleControlsInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyGuiScreenBase.HandleInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Game.Gui.MyGuiScreenTerminal.HandleInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyScreenManager.HandleInput()
   at Sandbox.Graphics.GUI.MyDX9Gui.HandleInput()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   at avaness.SpaceEngineersLauncher.Program.StartSpaceEngineers(String[] args)
   at avaness.SpaceEngineersLauncher.Program.Main(String[] args)
```

**Comment by Tiberias42** [comment]
Have not heard of more cases of this happening
