### ISSUE TITLE
WC Crash when "pasting something that intersected", but the Build Freedom mod allowed it to paste

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#743]
```

23:35:21.9299 [FATAL]  Initializer: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at CoreSystems.Support.Ai.RegisterSubGrid(MyCubeGrid grid)
   at CoreSystems.Support.Ai.SubGridChanges()
   at CoreSystems.GridGroupMap.UpdateAis()
   at CoreSystems.Support.CoreComponent.OnAddedToSceneTasks(Boolean firstRun)
   at CoreSystems.Support.CoreComponent.Init()
   at VRage.Game.Components.MyComponentBase.SetContainer(IMyComponentContainer container)
   at VRage.Game.Components.MyComponentContainer.Add(Type type, MyComponentBase component)
   at CoreSystems.Session.StartComps()
   at CoreSystems.Session.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 326
   at Torch.VRageGame.Run() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 126
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at CoreSystems.Support.Ai.RegisterSubGrid(MyCubeGrid grid)
   at CoreSystems.Support.Ai.SubGridChanges()
   at CoreSystems.GridGroupMap.UpdateAis()
   at CoreSystems.Support.CoreComponent.OnAddedToSceneTasks(Boolean firstRun)
   at CoreSystems.Support.CoreComponent.Init()
   at VRage.Game.Components.MyComponentBase.SetContainer(IMyComponentContainer container)
   at VRage.Game.Components.MyComponentContainer.Add(Type type, MyComponentBase component)
   at CoreSystems.Session.StartComps()
   at CoreSystems.Session.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 326
   at Torch.VRageGame.Run() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 126
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
   
   ```

**Comment by InvalidArgument3** [comment]
happened again when pasting a fighter block with a restriction radius on to a rotor within range of another one, narrowing it down

**Comment by InvalidArgument3** [comment]
[Sova_Carrier_StarCore_1.zip](https://github.com/StarCoreSE/SCModRepository/files/14553941/Sova_Carrier_StarCore_1.zip)
darth got a blueprint

**Comment by BDCarrillo** [comment]
Pretty sure I fixed this on 24 May

**Comment by InvalidArgument3** [comment]
yeah will need to update our fork
